{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mychart.serviceAccountName" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{/*---*/}}
{{/*apiVersion: rbac.authorization.k8s.io/v1beta1*/}}
{{/*kind: ClusterRoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "mychart.fullname" . }}-clusterrolebinding*/}}
{{/*subjects:*/}}
{{/*  - kind: ServiceAccount*/}}
{{/*    name: {{ include "mychart.serviceAccountName" . }}*/}}
{{/*    namespace: {{ .Release.Namespace }}*/}}
{{/*roleRef:*/}}
{{/*  kind: ClusterRole*/}}
{{/*  name: cluster-admin*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}

{{- end }}
