{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
{{- if .Values.sealedsecret.datasource.username }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.datasource.username }}
    password: {{ .Values.sealedsecret.datasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-datasource-cred
{{- end }}