---
#
# Usage
# ======
#
# First install needed tools:
# brew install pre-commit yamllint
#
# Then run:
# pre-commit run --all-files
#
# To install pre-commit hooks to your local repository, run:
# pre-commit install
#

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      #- id: check-yaml # does not work with helm chart templates
      - id: check-added-large-files
      - id: check-json

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        # needs to be disabled for helm chart templates
        args: ['-d' , '{extends: relaxed, ignore: ["**/templates/*.yaml","**/templates/*/*.yaml"], rules: {document-start: disable, line-length: {max: 120}}}']    

  - repo: local
    hooks:
    - id: helm-lint-all
      name: helm-lint-all
      entry: 'bash -c "helm lint $(find charts -maxdepth 1 -mindepth 1 -type d)"'
      language: system
      pass_filenames: false
      require_serial: true
