{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-init-datasource-cred

spec:
  encryptedData:
    username: {{ .Values.sealedsecret.initdatasource.username }}
    password:  {{ .Values.sealedsecret.initdatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-init-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.datasource.username }}
    password: {{ .Values.sealedsecret.datasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-ff4j-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.ff4j.username }}
    password: {{ .Values.sealedsecret.ff4j.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-ff4j-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-redis-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.redis.username }}
    password: {{ .Values.sealedsecret.redis.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-redis-cred