{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spicedb.serviceAccountName" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: {{ include "spicedb.fullname" . }}-watch-service
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch"]
---
apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name:  {{ include "spicedb.fullname" . }}-watch-service
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: "ServiceAccount"
    name: {{ include "spicedb.serviceAccountName" . }}
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: {{ include "spicedb.fullname" . }}-watch-service

{{- end }}
