apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  mountOptions:
    - nfsvers=3
  nfs:
    path: /DICCO-ESS-DEV_mssql-data-connect-evolution
    server: ps-dc2-nfs-tst-swing.global.dns
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs