{{- if .Values.grpc_ssl_enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mychart.fullname" . }}-grpc-service-tls
  namespace: {{ .Values.namespace }}
spec:
  secretName: {{ include "mychart.fullname" . }}-grpc-service-tls
  issuerRef:
    group: cert-manager.io
    name: cert-manager
    kind: ClusterIssuer
  usages:
  - digital signature
  - key encipherment  
  commonName: {{ .Values.grpc_dns_name }}
  dnsNames:
    - {{ .Values.dns_name }}
{{- end }}