{{- /* @formatter:off */}}
  {{- $fullName := include "mychart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers.waitForPulsar.enabled }}
      initContainers:
        - name: wait-for-pulsar
          image: nexus.global.dns:8443/ce/wait-for-pulsar-schemas:1.0
          args: ['{{ .Values.initContainers.waitForPulsar.topics }}']
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 5

          # use kustomize to specify env-vars per environment (tst, acc, prd); see kustomization.yml
          # dummy foo-bar added to make op 'add' in patch work correctly
          env:
            - name: DICCO_URL
              value: {{ .Values.env.dicco.url }}
            - name: DATASOURCE_JDBC-URL
              value: {{ .Values.env.datasource.jdbcurl }}
            - name: DATASOURCE_DATABASE-NAME
              value: {{ .Values.env.datasource.databasename }}
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.spring.profiles.active }}
            - name: SPRING_ELASTICSEARCH_URIS
              value: {{ .Values.env.spring.elasticsearch.uris }}
            - name: AXON_AXONSERVER_SERVERS
              value: {{ .Values.env.axon.axonserver.servers }}
            - name: SPRING_INIT-DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-init-datasource-cred
                  key: username
            - name: SPRING_INIT-DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-init-datasource-cred
                  key: password
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-datasource-cred
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-datasource-cred
                  key: password
            {{- if contains "dbeventstore" .Values.env.spring.profiles.active }}
            - name: SPRING_AXONDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-axonds-cred
                  key: username
            - name: SPRING_AXONDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-axonds-cred
                  key: password
            - name: AXONDS_JDBC-URL
              value: {{ .Values.env.axonds.jdbcurl }}
            - name: AXONDS_DATABASE-NAME
              value: {{ .Values.env.axonds.databasename }}
            {{- end }}
            - name: PULSAR_BROKER_URL
              value: {{ .Values.env.pulsar.broker.url }}
            - name: FF4J_API_URL
              value: {{ .Values.env.ff4j.api.url }}
            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.otel.exporter.otlp.endpoint }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: {{ .Values.env.otel.exporter.otlp.protocol }}
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: {{ .Values.env.otel.resource.attributes }}
            - name: OTEL_METRICS_EXPORTER
              value: {{ .Values.env.otel.metrics.exporter }}

            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
