{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-init-datasource-cred

spec:
  encryptedData:
    username: {{ .Values.sealedsecret.initdatasource.username }}
    password:  {{ .Values.sealedsecret.initdatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-init-datasource-cred

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.datasource.username }}
    password: {{ .Values.sealedsecret.datasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-datasource-cred

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-liquibase-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.liquibasedatasource.username }}
    password: {{ .Values.sealedsecret.liquibasedatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-liquibase-datasource-cred
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-dicco-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.diccodatasource.username }}
    password: {{ .Values.sealedsecret.diccodatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-dicco-datasource-cred

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-redis-cred

spec:
  encryptedData:
    password:  {{ .Values.sealedsecret.redis.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-redis-cred
