{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-init-datasource-cred

spec:
  encryptedData:
    username: {{ .Values.sealedsecret.initdatasource.username }}
    password:  {{ .Values.sealedsecret.initdatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-init-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.datasource.username }}
    password: {{ .Values.sealedsecret.datasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-datasource-cred

---
{{- if contains "dbeventstore" .Values.env.spring.profiles.active }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-axonds-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.axonds.username }}
    password: {{ .Values.sealedsecret.axonds.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-axonds-cred
{{- end }}