apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - name: debug
      port: 5006
      protocol: TCP
      targetPort: 5006
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}