apiVersion: v2
appVersion: 1.52.0
description: Helm chart for ce-calendar-perftest
name: ce-calendar-perftest
type: application
version: 0.59.0
dependencies:
- name: redis
  version: 18.1.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
- name: mysql
  version: 9.19.1
  repository: https://charts.bitnami.com/bitnami
  condition: mysql.enabled
