apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: p-6123-6123-tcp
      port: 6123
      protocol: TCP
      targetPort: 6123
    - name: p-8081-8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    {{- include "mychart.selectorLabels" . | nindent 4 }}