{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.datasource.username }}
    password: {{ .Values.sealedsecret.datasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-liquibase-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.liquibasedatasource.username }}
    password: {{ .Values.sealedsecret.liquibasedatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-liquibase-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-dicco-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.diccodatasource.username }}
    password: {{ .Values.sealedsecret.diccodatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-dicco-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-calendar-axon-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.calendaraxondatasource.username }}
    password: {{ .Values.sealedsecret.calendaraxondatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-calendar-axon-datasource-cred

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-repertorium-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.repertorium.username }}
    password: {{ .Values.sealedsecret.repertorium.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-repertorium-datasource-cred