{{- /* @formatter:off */}}
  {{- $fullName := include "mychart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tempo.enabled }}
        instrumentation.opentelemetry.io/inject-sdk: "open-telemetry/default-sdk-{{ .Values.tempo.tenant }}"
      {{- end }}
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
        {{- if .Values.loki.enabled }}
        loki: connect-{{ .Values.loki.tenant }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 100
            periodSeconds: 5

          # use kustomize to specify env-vars per environment (tst, acc, prd); see kustomization.yml
          # dummy foo-bar added to make op 'add' in patch work correctly
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.spring.profiles.active }}
            - name: EXTERNAL_BALANCESAPI_CLIENT_CLIENTID
              value: {{ .Values.env.external.balancesApi.oauth2.clientId }}
            - name: EXTERNAL_BALANCESAPI_CLIENT_CLIENTSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-api-client-secret
                  key: apiClientSecret
            - name: EXTERNAL_BALANCESAPI_CLIENT_TOKENURI
              value: {{ .Values.env.external.balancesApi.oauth2.tokenUri }}
            - name: EXTERNAL_BALANCESAPI_CLIENT_BASEURL
              value: {{ .Values.env.external.balancesApi.baseUrl }}
            - name: WEBCOMPONENT_HOST
              value: {{ .Values.env.webcomponent.host }}
            - name: FF4J_API_URL
              value: {{ .Values.env.ff4j.api.url }}
            - name: OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_METRICS_EXPORTER
              value: none

            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
