{{- /* @formatter:off */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ - include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.pactImageRepository | lower }}:{{ .Values.image.pactImageTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: PACT_BROKER_DATABASE_HOST
              value: {{ template "pact-broker.postgresql.fullname" . }}
            - name: PACT_BROKER_DATABASE_NAME
              value: {{ .Values.postgresql.postgresDatabase }}
            - name: PACT_BROKER_DATABASE_USERNAME
              value: {{ .Values.postgresql.postgresUser }}
            - name: PACT_BROKER_DATABASE_PASSWORD
              value: {{ .Values.postgresql.postgresPassword }}             
            - name: PACT_BROKER_PORT 
              value: "9292"    
              
          livenessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probePath }}
              port: {{ .Values.service.internalPort }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
