apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-config
  namespace: {{ .Values.namespace }}
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 8443
        filter_chains:
     

        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              codec_type: auto
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /dev/stdout

              http2_protocol_options: {}
              upgrade_configs:
              - upgrade_type: CONNECT
              - upgrade_type: websocket
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: local_service
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/calendar-timespend/socket"
                    route:
                      cluster: frontend_services_gateway_ws
                      upgrade_configs:
                      - upgrade_type: websocket
                        enabled: true
                  - match:
                      prefix: "/calendar-timespend/perftest"    
                    route:
                      cluster: frontend_services_gateway_ws
                      upgrade_configs:
                      - upgrade_type: websocket
                        enabled: true
                  - match:
                      prefix: "/calendar-balance/socket"    
                    route:
                      cluster: frontend_services_gateway_ws
                      upgrade_configs:
                      - upgrade_type: websocket
                        enabled: true                                                                        
                  - match:
                      prefix: "/"
                    route:
                      cluster: frontend_services_gateway
              
                
                
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                alpn_protocols: "h2"
                tls_certificates:
                - certificate_chain:
                    filename: "/etc/envoy/ssl/tls.crt"
                  private_key:
                    filename: "/etc/envoy/ssl/tls.key"
      clusters:
      - name: frontend_services_gateway
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        http2_protocol_options: {} # enable H2 protocol
        
        load_assignment:
          cluster_name: frontend_services_gateway
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: frontend-services-gateway.connect-evolution-inttst.svc.cluster.local
                    port_value: 8080

      - name: frontend_services_gateway_ws
        connect_timeout: 0.25s
        type: strict_dns
        lb_policy: round_robin
        # http2_protocol_options: {} # disabled for websocket to work
        
        load_assignment:
          cluster_name: frontend_services_gateway
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: frontend-services-gateway.connect-evolution-inttst.svc.cluster.local
                    port_value: 8080                    
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901