---
apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.name }}-service
    namespace: {{ .Values.namespace }}
    annotations:
        external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns_name }}
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
    type: LoadBalancer
    selector:
        app: {{ .Values.name }}
    ports:
        - name: https
          protocol: TCP
          port: 443
          targetPort: 8443