{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
        {{- if .Values.loki.enabled }}
            {{- if .Values.loki.multiline }}
        lokiml: acerta-payroll-service-{{ .Values.loki.tenant }}
            {{- else }}
        loki: acerta-payroll-service-{{ .Values.loki.tenant }}
            {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ['migrate head']
          restartPolicy: OnFailure
          env:
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.spicedb.datastore.secretName }}
                  key: "spicedb_datastore_conn_uri"
            - name: SPICEDB_DATASTORE_ENGINE
              value: {{ .Values.spicedb.datastore.engine }}
            - name: SPICEDB_LOG_LEVEL
              value: "debug"
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8443
            - containerPort: 9090
            - containerPort: 50051
          env:
            - name: SPICEDB_DATASTORE_CONN_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.spicedb.datastore.secretName }}
                  key: "spicedb_datastore_conn_uri"
            - name: SPICEDB_DATASTORE_ENGINE
              value: {{ .Values.spicedb.datastore.engine }}
            - name: SPICEDB_LOG_LEVEL
              value: {{ .Values.spicedb.loglevel }}
            - name: SPICEDB_GRPC_NO_TLS
              value: {{ .Values.spicedb.grpc.notls }}
            - name: SPICEDB_HTTP_ENABLED
              value:  {{ .Values.spicedb.http.enabled }}
            - name: SPICEDB_GRPC_SHUTDOWN_GRACE_PERIOD
              value: "1s"
            - name: SPICEDB_DATASTORE_BOOTSTRAP_OVERWRITE
              value: "true"
            - name: SPICEDB_TELEMETRY_ENDPOINT
              value: {{ .Values.spicedb.telemetry.endpoint }}
            - name: SPICEDB_GRPC_PRESHARED_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.spicedb.grpc.preshared.secretName }}
                  key: "spicedbpresharedkey"
            {{- range $key, $value := $.Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
