apiVersion: v1
kind: Service
metadata:
  name: {{ include "spicedb.fullname" . }}
  labels:
    {{- include "spicedb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.spicedb.grpc.enabled }}
    - port: {{ .Values.spicedb.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if .Values.spicedb.http.enabled }}
    - port: {{ .Values.spicedb.http.port }}
      protocol: TCP
      targetPort: http
      name: http
    {{- end }}
    {{- if .Values.spicedb.dispatch.enabled }}
    - port: {{ .Values.spicedb.dispatch.port }}
      targetPort: dispatch
      protocol: TCP
      name: dispatch
    {{- end }}
    {{- if .Values.spicedb.metrics.enabled }}
    - port: {{ .Values.spicedb.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "spicedb.selectorLabels" . | nindent 4 }}