apiVersion: v1
kind: Service
metadata:
  name: {{ template "tempo.fullname" . }}-grpc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
{{/*  {{- if .Values.service.loadBalancerSourceRanges }}*/}}
{{/*  loadBalancerSourceRanges:*/}}
{{/*    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}*/}}
{{/*  {{- end -}}*/}}
  ports:
    - name: grpc-tempo-otlp
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}

