apiVersion: v1
kind: ConfigMap
metadata:
  name: realm-{{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}

data:
  {{- if .Values.acerta_realm_json }}
  acerta-realm.json: {{ toYaml .Values.acerta_realm_json | indent 4 }}
  {{- end }}
  {{- if not .Values.acerta_realm_json }}
  acerta-realm.json: {{ toYaml .Values.acerta_realm_json | indent 4 }}
  {{- end }}