apiVersion: v1
kind: ConfigMap
metadata:
  name: realm-{{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
data:
  acerta-realm.json: |
      {{ .Values.acerta_realm_json }}