{{- /* @formatter:off */}}
{{- $fullName := include "mychart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-gateway-client-secret

spec:
  encryptedData:
    secret: {{ .Values.sealedsecret.gatewayclient.secret }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-gateway-client-secret
