apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connectfrontend.fullname" . }}
  labels:
    {{- include "connectfrontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "connectfrontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "connectfrontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "connectfrontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /AES/actuator/health
              port: 8080
          readinessProbe:
            httpGet:
              path: /AES/actuator/health
              port: 8080
          startupProbe:
            httpGet:
              path: /AES/actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: TZ
              value: "Europe/Brussels"
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/tomcat/external
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "connectfrontend.fullname" . }}
            items:
              - key: CSD.xml
                path: CSD.xml
              - key: ehcache.xml
                path: ehcache.xml
              - key: KEY.xml
                path: KEY.xml
              - key: log4j.xml
                path: log4j.xml
              - key: THD.xml
                path: THD.xml
              - key: workplace.properties
                path: config/properties/workplace.properties

        {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
