{{- /* @formatter:off */}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: savepoints-data
{{- if .Values.sharedPersistence.annotations }}
  annotations:
{{ toYaml .Values.sharedPersistence.annotations | indent 4 }}
{{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.sharedPersistence.dataAccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.sharedPersistence.dataSize | quote }}
{{- if .Values.sharedPersistence.storageClass }}
{{- if (eq "-" .Values.sharedPersistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.sharedPersistence.storageClass }}"
{{- end }}
{{- end }}