{{- /* @formatter:off */}}
  {{- $fullName := include "mychart.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config-map: {{ include (print $.Template.BasePath "/spring-config.yaml") . | sha256sum   }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.tempo.enabled }}
        instrumentation.opentelemetry.io/inject-sdk: "open-telemetry/default-sdk-{{ .Values.tempo.tenant }}"
      {{- end }}
      labels:
        {{- include "mychart.selectorLabels" . | nindent 8 }}
        {{- if .Values.loki.enabled }}
            {{- if .Values.loki.multiline }}
        lokiml: acerta-payroll-service-{{ .Values.loki.tenant }}
            {{- else }}
        loki: acerta-payroll-service-{{ .Values.loki.tenant }}
            {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - configMap:
            name: application-yml-{{ include "mychart.fullname" . }}
          name: application-yml
        - name: ssl-certs
          secret:
            secretName: {{ .Values.name }}-tls
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - mountPath: /app/config
              name: application-yml
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https-alt
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: https-alt
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http-grpc-alt
            failureThreshold: 30
            periodSeconds: 5

          # use kustomize to specify env-vars per environment (tst, acc, prd); see kustomization.yml
          # dummy foo-bar added to make op 'add' in patch work correctly
          env:
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_CE-GATEWAY_ClIENT-SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-gateway-client-secret
                  key: secret
            - name: OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_METRICS_EXPORTER
              value: none
            {{- if .Values.ingress.http.enabled -}}
            {{- range .Values.ingress.http.hosts }}
            - name: SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL
              value: https://{{ .host }}
            {{- end }}
            {{- end }}
            {{- if .Values.extraEnvs }}
              {{- toYaml .Values.extraEnvs | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
