ce-calendar-timespend-backend:
  enabled: true

ce-calendar-timespend-frontend:
  enabled: true

pulsar-client:
  enabled: true

pulsar-init-job:
  enabled: true

ce-ff4j-server:
  enabled: true

ce-webcomponents:
  enabled: true

ce-repertoriumservice:
  enabled: true

ce-balances:
  enabled: true

ce-clink:
  enabled: true

ce-init-load:
  enabled: true

frontend-services-gateway:
  enabled: true

ce-calendar-balance-backend:
  enabled: true

ce-calendar-balance-frontend:
  enabled: true
