{{- /* @formatter:off */}}
  {{- $fullName := include "mychart.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-init-datasource-cred

spec:
  encryptedData:
    username: {{ .Values.sealedsecret.initdatasource.username }}
    password:  {{ .Values.sealedsecret.initdatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-init-datasource-cred

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-calendar-axon-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.calendaraxondatasource.username }}
    password: {{ .Values.sealedsecret.calendaraxondatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-calendar-axon-datasource-cred

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-timespend-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.timespenddatasource.username }}
    password: {{ .Values.sealedsecret.timespenddatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-timespend-datasource-cred

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ $fullName }}-balance-datasource-cred
spec:
  encryptedData:
    username: {{ .Values.sealedsecret.balancedatasource.username }}
    password: {{ .Values.sealedsecret.balancedatasource.password }}
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ $fullName }}-balance-datasource-cred

