name: Publish Helm Chart to Harbor

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:
  publish-to-harbor:
    runs-on: [ self-hosted, devtst-ce ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.0

      - name: Log in to Harbor
        run: |
          echo ${{ secrets.HARBORSTG_PASSWORD }} | \
          helm registry login harbor.toolsstg.acerta.io -u ${{ secrets.HARBORSTG_USERNAME }} --password-stdin

      - name: Dependency build
        run: |
          for dir in charts/*; do
            helm dep update "$dir"
          done

      - name: Package Helm chart
        run: |
          for dir in charts/*; do
            helm package "$dir"
          done

      - name: Dependency build ce-helm-charts
        run: |
          for dir in charts-harbor/*; do
            helm dep update "$dir"
          done

      - name: Package Helm chart  ce-helm-charts
        run: |
          for dir in charts-harbor/*; do
            helm package "$dir"
          done

      - name: Push Helm charts to Harbor
        run: |
          for chart in *.tgz; do
            helm push "$chart" oci://harbor.toolsstg.acerta.io/connect-evolution
          done
