name: Release Charts

on:
  push:
    branches:
      - main
      - 'hotfix/**'
      
concurrency: ci-sequential

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
#      - name: Sleep 1 minute
#        run: sleep 60s
        # temp? fix to let preceding releases finish

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        # https://github.com/helm/chart-releaser-action/releases
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
