name: Release Helm Charts

run-name: DEV ${{ github.actor }} is releasing new Helm charts.

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - hotfix/**
    paths:
    - charts/**

jobs:
  release:
    runs-on: okteto
    steps:

    - name: 'Git Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Configure & Install Helm'
      uses: azure/setup-helm@v3

    - name: Authorize with Harbor
      run: |
        echo ${{ secrets.HARBOR_RELEASE_PASSWORD }} | helm registry login -u ${{ secrets.HARBOR_RELEASE_USER }} --password-stdin harbor.tools.acerta.io/acerta-releases/acerta-connect-evolution/charts