name: Testing Release Charts

on:
  push:
    branches:
      - main
      - 'release/**'


jobs:
  release:
    runs-on: ubuntu-latest
    if: false == startsWith(github.event.pull_request.head.ref, 'hotfix/') 
      steps:
        - name: Succesfull
          run: echo "Build succesfull"
    else:
      steps:
      - name: Succesfull
        run: echo "Build succesfull"
