mssql-latest:
  fullnameOverride: mssql-latest
  enabled: true
  persistence:
    dataSize: 1Gi
    userlogSeparateClaim: false
    tempSeparateClaim: false
    userdbSeparateClaim: false

elasticsearch:
  fullnameOverride: elasticsearch-master
  enabled: true
  image: nexus.global.dns:8443/acerta-dev/elasticsearch
  imageTag: 7.15.0
  replicas: 2
  minimumMasterNodes: 1
  volumeClaimTemplate.resources.requests.storage: 1Gi
  sysctlInitContainer.enabled: false
  extraEnvs:
    - name: TZ
      value: Europe/Brussels
  ingress:
    className: ""
    enabled: true
    annotations:
      dev.okteto.com/generate-host: "true"
      kubernetes.io/ingress.class: nginx

redis:
  fullnameOverride: redis
  enabled: true
  architecture: standalone
  global:
    redis:
      password: Admin123

pulsar-standalone:
  fullnameOverride: pulsar-standalone
  enabled: true
  ingress:
    className: ""
    enabled: true
    annotations:
      dev.okteto.com/generate-host: "true"
  resources:
    requests:
      cpu: "500m"
      memory: "2048Mi"
    limits:
      memory: "4096Mi"
      cpu: "1000m"

pulsar-admin-console:
  fullnameOverride: pulsar-admin-console
  enabled: true
  local_json: |
    {
        "auth_mode": "none",
        "cluster_name": "standalone",
        "tenant": "public",
        "oauth_client_id": "",
        "server_config": {
            "port": "6454",
            "pulsar_url": "http://pulsar-standalone:8080",
            "websocket_url": "https://websocket.example.com:8500",
            "function_worker_url": "",
            "log_level": "info",
            "token_path": "",
            "admin_token": "",
            "token_secret": "",
            "ssl": {
                "verify_certs": true,
                "hostname_validation": true,
                "ca_path": "",
                "cert_path": "",
                "key_path": ""
            },
            "kubernetes": {
                "k8s_namespace": "pulsar",
                "kubernetes_service_host": "",
                "service_port": ""
            },
            "user_auth": {
                "username": "",
                "password": ""
            },
            "oauth2": {
                "identity_provider_url": "",
                "token_endpoint": "",
                "grant_type": "password"
            }
        },
        "polling_interval": "10000",
        "ca_certificate": "",
        "api_version": "2.8.3",
        "notice_text": "",
        "functions_disabled": "false",
        "render_monitoring_tab": "false",
        "grafana_url": "",
        "clients_disabled": "false",
        "host_overrides": {
            "pulsar": "http://localhost:6650",
            "ws": "ws://localhost:8080",
            "http": "http://localhost:8964"
        }
    }
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"

pulsar-client:
  fullnameOverride: pulsar-client
  enabled: true
  env:
    pulsar:
      adminurl: http://pulsar-standalone:8080
      allowedclusters: standalone
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"

ce-ff4j-server:
  fullnameOverride: ce-ff4j-server
  enabled: true
  env:
    ff4jserver:
      elasticSearchUrl: http://elasticsearch-master:9200
      elasticSearchContext: not_used_yet
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"

ce-repertoriumservice:
  fullnameOverride: ce-repertoriumservice
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"

pulsar-init-job:
  fullnameOverride: pulsar-init-job
  enabled: true
  initContainers:
    waitForUrl:
      enabled: true
      endpoint: pulsar-standalone:8080/admin/v2/brokers/health;pulsar-client:8080/actuator/health
  script: ""

ff4j-init-job:
  fullnameOverride: ff4j-init-job
  enabled: true
  initContainers:
    waitForUrl:
      enabled: true
      endpoint: ce-ff4j-server:8080
  script: ""

frontend-services-gateway:
  fullnameOverride: frontend-services-gateway
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"
  application_yml: ""

keycloak-boot:
  fullnameOverride: keycloak-boot
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"
  extraEnv:
    REALM_IMPORT_FILE: "file:///config/acerta-realm.json"
    GATEWAY_SUBDOMAIN_SUFFIX: "-${OKTETO_NAMESPACE}"
    GATEWAY_DOMAIN: ".tst.connectevolution.global.dns"
    TZ: "Europe/Brussels"

ce-webcomponents:
  fullnameOverride: ce-webcomponents
  enabled: true
  image:
    tag: "latest"
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"

ce-fake-everesst:
  fullnameOverride: ce-fake-everesst
  enabled: true
  ingress:
    enabled: true
    className: ""
    annotations:
      dev.okteto.com/generate-host: "true"
  application_yml: |
    # Server
    spring.application.name: ce-fake-everesst
    server:
      port: 8080
      compression.enabled: true
    
    ---
    # Actuator
    management:
      endpoint.health.show-details: always
      endpoints.web.exposure.include: "*"
    
    ---
    # Pulsar
    pulsar:
      enabled: true
      broker.url: pulsar://pulsar-standalone:6650
      defaults:
        consumer:
          tenant: acerta
          namespace: payroll
        producer:
          tenant: everesst
          namespace: payroll
      consumers:
        PulsarAdjustmentBookedIntegrationEventHandler:
          subscription:
            topic: employee-out-fake
      producers:
        WorktimePrioritizationCalculatedIntegrationEventPublisher:
          topic: worktime
